version: '3'
services:
  db:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./fortress_master_data:/bitnami"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
