version: '3'
services:
  web:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "3000:3000"
    networks:
      - app-tier

  db:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./fortress_master_data:/bitnami"
    networks:
      - app-tier

       
networks:
  app-tier:
    driver: bridge
